name: Feature and Training Unit and Integration Tests for mlops_project_demo
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'mlops_project_demo/**'
      - '.github/workflows/mlops_project_demo-run-tests.yml'

defaults:
  run:
    working-directory: ./mlops_project_demo/

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

concurrency: mlops_project_demo-feature-training-integration-test-staging

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.7
      # Feature store tests bring up a local Spark session, so Java is required.
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r ../test-requirements.txt
      # - name: Run tests with pytest
      #   run: |
      #       pytest

  integration_test:
    needs: unit_tests
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.245.0
      - name: Validate Bundle For Test Deployment Target in Staging Workspace
        id: validate
        run: |
          databricks bundle validate -t staging
      - name: Deploy Bundle to Test Deployment Target in Staging Workspace
        id: deploy
        run: |
          databricks bundle deploy -t staging
      - name: Run Feature Engineering Workflow for Test Deployment Target in Staging Workspace
        id: feature_engineering
        run: |
          databricks bundle run write_feature_table_job -t staging
      - name: Run Training Workflow for Test Deployment Target in Staging Workspace
        id: training
        run: |
          databricks bundle run model_training_job -t staging
      - name: Run Batch Inference Workflow for Test Deployment Target in Staging Workspace
        id: batch_inference
        run: |
          databricks bundle run batch_inference_job -t staging
      - name: Run Model Serving Workflow for Test Deployment Target in Staging Workspace
        id: model_serving_endpoint
        run: |
          databricks bundle run deploy_model_serving_endpoint_job -t staging
